### ISSUE TITLE
[Feature] Support to edit channel by /data

### ISSUE THREAD

**Issue by IceCola97** [SuperMartijn642/Tesseract#102]
I've noticed that the data for the Tesseract block includes the sending direction and redstone control, but there is no part that allows specifying the activation sending channel. I am placing this block in batches and hope to configure all Tesseract blocks uniformly, requiring such a feature. My version is 1.21.1 Fabric, I'm asking if this is possible?

**Comment by SuperMartijn642** [comment]
I am not completely sure what you mean. Do you want to set tesseract data using a command?

**Comment by IceCola97** [comment]
> I am not completely sure what you mean. Do you want to set tesseract data using a command?

Yes, of course, it would be even better if there were other ways to configure in bulk.

**Comment by SuperMartijn642** [comment]
The reason I asked about a command was since you mentioned '/data' in the title. So I assumed you were using some command and it wasn't working with tesseracts.

Tesseract data which determines whether a tesseract can send or receive items/fluids/energy is stored in a separate system and not on the block entity. This is to avoid chunk loading when transferring things between tesseracts.
However, this shouldn't matter from a player perspective. Are you doing something with the save data from block entities?

As for configuring tesseracts in bulk, what is you use case? I would think this is something most players won't use and I can't really think of a good way that doesn't require adding a specific item or that isn't intrusive for players who don't care about such a feature.

**Comment by IceCola97** [comment]
> The reason I asked about a command was since you mentioned '/data' in the title. So I assumed you were using some command and it wasn't working with tesseracts.
> 
> Tesseract data which determines whether a tesseract can send or receive items/fluids/energy is stored in a separate system and not on the block entity. This is to avoid chunk loading when transferring things between tesseracts. However, this shouldn't matter from a player perspective. Are you doing something with the save data from block entities?
> 
> As for configuring tesseracts in bulk, what is you use case? I would think this is something most players won't use and I can't really think of a good way that doesn't require adding a specific item or that isn't intrusive for players who don't care about such a feature.

Alright,if it's not feasible in terms of design,then let it be.My approach is to attempt to use many individual item storage units to stack and form a large-scale fully automatic item management framework.In this process,many new items from mods need to be constructed and stored by robots themselves,so having a unified and simple logistics system is crucial.The Tesseract block is a rather ideal solution in the current version,so I hope to make the most of it.
