### ISSUE TITLE
[1.16.1] Tesseract Item Transfer Issue

### ISSUE THREAD

**Issue by CrossVas** [SuperMartijn642/Tesseract#15]
I know that there is a closed issue about this, but it didn't get anywhere, so I decided to create a new issue. 
I enjoying playing with Mekanism and Tesseract mod on 1.16.1, but there is an issue with Tesseract. 
So, the problem is that Tesseract won't accept item from mekanism's pipes. 

Setup: 
MC Version: 1.16.1
Forge Version: 32.0.108
Tesseract Version: 1.0.12-mc1.16.1

First setup: Item source (in this case > Creative Bin) - Logistical Transporter (pull from Bin) - Tesseract - Logistical Transporter - Bin > Doesn't work.
![2020-08-30_13 23 03](https://user-images.githubusercontent.com/25727222/91656958-de76b580-eac5-11ea-8f4a-76ca3e004ba4.png)

Second setup: Item source (in this case > Creative Bin) - Logistical Transporter (pull from Bin) - Hopper - Tesseract - Logistical Transporter - Bin > Works.
![2020-08-30_13 23 12](https://user-images.githubusercontent.com/25727222/91657002-4af1b480-eac6-11ea-8450-68106c747433.png)

If I am missing something or it is not a Tesseract Mod's problem, please, let me know. 
Thanks!

EDIT: Did a check with fluids, works just fine
![2020-08-30_13 51 34](https://user-images.githubusercontent.com/25727222/91657230-1f6fc980-eac8-11ea-8c83-4ac58bd3326e.png)

**Comment by SuperMartijn642** [comment]
Forge provides an interface for blocks which store items, IItemHandler. The tesseracts check for IItemHandlers around them and are themselves an IItemHandler.
The pipes from Mekanism extract from and put items into IItemHandlers they are connected with, but the pipes themselves don't have an IItemHandler.
When a pipe tries to pull items from a tesseract, the tesseract doesn't find any IItemHandlers at the other end, same when the pipes try to put items into a tesseract.

To combat this you can put an IItemHandler at either end, just a chest for example will do.
![tesseract item demo2](https://user-images.githubusercontent.com/12382965/91661003-9feaf600-ead9-11ea-9936-5f78d3ddc9a5.gif)
Here shown with EnderIO conduits, but it should be the same for Mekanism pipes.

It does work with the mechanical pipes, because they work differently from the logistical pipes and have an IFluidHandler.

The only way to make it work would be to specifically add compatibility for every mod that adds its own pipes. That, however, would take too much of my time and I would need to update Tesseract every time one of those mods updates.

**Comment by CrossVas** [comment]
Very thankful for your answer. The issue can be closed.

**Comment by P3rf3ctXZer0** [comment]
> 
> 
> Forge provides an interface for blocks which store items, IItemHandler. The tesseracts check for IItemHandlers around them and are themselves an IItemHandler.
> The pipes from Mekanism extract from and put items into IItemHandlers they are connected with, but the pipes themselves don't have an IItemHandler.
> When a pipe tries to pull items from a tesseract, the tesseract doesn't find any IItemHandlers at the other end, same when the pipes try to put items into a tesseract.
> 
> To combat this you can put an IItemHandler at either end, just a chest for example will do.
> ![tesseract item demo2](https://user-images.githubusercontent.com/12382965/91661003-9feaf600-ead9-11ea-9936-5f78d3ddc9a5.gif)
> Here shown with EnderIO conduits, but it should be the same for Mekanism pipes.
> 
> It does work with the mechanical pipes, because they work differently from the logistical pipes and have an IFluidHandler.
> 
> The only way to make it work would be to specifically add compatibility for every mod that adds its own pipes. That, however, would take too much of my time and I would need to update Tesseract every time one of those mods updates.

This should be on the front page of your mod. When I first tried tesseract I honestly thought it was broken.
