### ISSUE TITLE
Ender IO - 1.12.2

### ISSUE THREAD

**Issue by mauricederbaum** [SuperMartijn642/Tesseract#20]
Ender IO conduits can extract but not Insert items into the Tesseract

**Comment by SuperMartijn642** [comment]
Please note that you will need an inventory at one of the tesseracts. Sadly there's not really anything I can do about that.
![tesseract item demo2](https://user-images.githubusercontent.com/12382965/105058856-f354e500-5a76-11eb-9af1-22fe5a93e396.gif)
When I do that it seems to work fine for me. I hope that was the problem, otherwise let me know.

**Comment by SuperMartijn642** [comment]
I assume that was the issue then.
If not, please comment and I will reopen the issue.
