### ISSUE TITLE
[Bug] Tesseracts load chunks

### ISSUE THREAD

**Issue by Michael-Hozza** [SuperMartijn642/Tesseract#21]
**Version Info**
- Minecraft, 1.12.2
- Tesseract, tesseract-1.0.17-mc1.12

**Description of the Bug**
When placing down 2 tesseracts separately in the world, chunks should be unloaded => tesseracts won't work, until both chunks are loaded at the same time. When opening gui of loaded tesseract, all connected tesseract become loaded until I force it to unload.
**Steps to Reproduce**
Place 2 tesseracts in different places, load only one tesseract and rightclick on it, second one will load and chunkload chunk placed into.

**Comment by SuperMartijn642** [comment]
What I have tested:
- I place a repeating command block sending a chat message every tick in the chunk at (x=1000,z=1000)
- I place a tesseract in the chunk at (x=1000,z=1000) set to item channel '1'
- I place a tesseract in the chunk at (x=0,z=0) set to item channel '1'
- I reload the world
- I rightclick on the tesseract in the chunk at (x=0,z=0)

When doing this I never get a chat message from the command block, thus the chunk at (x=1000,z=1000), where the other tesseract is, does not get loaded.

Are there any other requirements in order to reproduce the issue?

**Comment by bigenergy** [comment]
it seems I faced the same problem, after installing tesseract on my server there are too many loaded chunks

**Comment by P3rf3ctXZer0** [comment]
Just use a chunk loader and this is intended for performance reasons you can always use FTB chunk loading ... a mod messing with chunk loading can be disastrous. This is not an issue.

**Comment by SuperMartijn642** [comment]
Kinda forgot about this issue, I believe this issue has been addressed and it is no longer relevant.
