### ISSUE TITLE
[Bug] Fluids and items not transferring

### ISSUE THREAD

**Issue by Leafgard** [SuperMartijn642/Tesseract#38]
**Version Info**
- FTB Ultimate Anniversary Edition v1.3.0
- Tesseract v1.0.24

**Description of the Bug**
Energy is transfering properly, but **not fluids nor items**.

**Steps to Reproduce**
Based on the screenshot below:

Each row has a unique channel to test transfer, that means:
- ENERGY, not restricted
- FLUID, not restricted
- ITEMS, not restricted

As you can see, **pipes are on extract mode as they should**, energy is transfering properly, but fluids and items just **won't transfer at all**, even playing with the settings.

**Screenshots**
![2022-03-12_22 13 51](https://user-images.githubusercontent.com/25567034/158035307-40382e18-dddc-4f89-b706-32ab2659cda8.png)

**Comment by SuperMartijn642** [comment]
Forge provides interfaces for blocks which store items or liquids, IItemHandler and IFluidHandler respectively. The tesseracts check for IItemHandlers and IFluidHandlers around them and are themselves an IItemHandler and IFluidHandler.
Pipez' pipes extract from and put items/fluids into IItemHandlers/IFluidHandler they are connected with, but the pipes themselves don't have an IItemHandler/IFluidHandler.
When a pipe tries to pull items/fluids from a tesseract, the tesseract doesn't find any IItemHandlers/IFluidHandlers at the other end, same when the pipes try to put items/fluids into a tesseract.

To combat this you can put an IItemHandler/IFluidHandler at either end. This can simply be a chest/tank or machine.
![](https://user-images.githubusercontent.com/12382965/91661003-9feaf600-ead9-11ea-9936-5f78d3ddc9a5.gif)
Here shown with EnderIO conduits, but it should be the same for other pipes and with fluids.
In your image, simply place the tesseract directly against the blocks at one end, i.e. without pipes in between at one end.

It does work for energy, because most energy pipes do actually implement the IEnergyStorage interface.

**Comment by Leafgard** [comment]
Hey @SuperMartijn642, thanks for the answer, understood ! 🚀 

Have a nice day ! 😄

**Comment by cTurtle98** [comment]
does the sending side need the chest or the receiving side?
