### ISSUE TITLE
Tesseract not accepting pipe input

### ISSUE THREAD

**Issue by FinestBlue** [SuperMartijn642/Tesseract#44]
I've tried using Pipez mod pipes and mekanism pipes but I cant get either to send items through the tesseract. It only works if directly hooked up to an inventory that pushes into it, like a digital miner (with no pipes) As far as I can tell you cant pipe items into it. Im playing on the latest version of Direwolf 20 1.18 modpack. 

The reason this is an issue is because I would like to tesseract from a builder into my RS system in another dimension. But if you put the tesseract on top of the builder to use it like a chest it instantly takes the quarry shape card out of the builder which it needs to function.

**Comment by SuperMartijn642** [comment]
The tesseract looks for inventories around itself. Pipes usually don't have an inventory, thus it won't find them.
To get around this you simply need an inventory at one end and use pipes to push/pull at the other end.
Usually it's easiest to place the tesseract directly against the thing you are trying to push to/pull from.

![](https://media.discordapp.net/attachments/779005278272225300/977894211523321856/unknown.png)

**Comment by PHI-AM** [comment]
I am trying to connect a quarry (BuildCraft Builders) with a Tesseract using Cobblestone Transport Pipes (BuildCraft Transport). However, you can see the item going through the pipe, reaching the tesseract and turning around to get kicked out of the pipe. Same happens if you directly connect the Tesseract to the Quarry. I assume its because it doesn't have inventory. Is there a way to do this? I remember a tesseract from the old days (maybe a different mod?) that was able to do it.

Thanks in advance.
Game Version: 1.12.2
Modpack: Infinity Evolved Reloaded 3.9.0

**Comment by SuperMartijn642** [comment]
Closing due to no response.

**Comment by Wubzzz1337** [comment]
I tried ur way of doing this but it doesn't seem to work for some reason.
Am I doing something wrong?

https://streamable.com/2bduin

**Comment by SuperMartijn642** [comment]
Look at the image I sent, you'll need pipes to either push to/pull from the tesseract. It's as if those pipes are then directly pushing to/pulling from any inventories touching the tesseract at the other end.
