### ISSUE TITLE
[Bug] Tesseract not sending Power

### ISSUE THREAD

**Issue by Dynamicuno55** [SuperMartijn642/Tesseract#59]
**Version Info**
- Minecraft, 1.18.2
- Tesseract, 1.0.27-forge-mc1.18

**Description of the Bug**
Tesseracts set up to transfer power with one set to send only and other set to receive only. Despite the proper setup (as confirmed by mod operator), no power is being sent through the tesseracts

**Steps to Reproduce**
Using Mekanism wind generators and power cables, whether the tesseract is hooked up directly to the generators or to power cables, and then trying to connect the receiving tesseract to any other machine, it does not send any power

**Screenshots**
![image](https://user-images.githubusercontent.com/118128828/201537285-119aacfb-0d92-49bc-af09-f554d486a23c.png)
![image](https://user-images.githubusercontent.com/118128828/201537291-0621ffea-afa7-4548-b2a2-b71b4deaa76b.png)

**Comment by Worive** [comment]
I have the same setup but working on my side.

If the chunks are apart, be sure that both are loaded

**Comment by rlnt** [comment]
@SuperMartijn642 Is there any plan to fix these random issues in the near future? The tesseracts are pretty unusable otherwise. It feels really random that they stop sending sometimes. But them stopping to send energy after a server restart is 100% reproducible for me.

**Comment by SuperMartijn642** [comment]
> It feels really random that they stop sending sometimes. But them stopping to send energy after a server restart is 100% reproducible for me.

That does not sound like what this issue is about. If that's what you're experiencing, please create a separate issue with the appropriate information and steps to reproduce.

> Is there any plan to fix these random issues in the near future?

No. Issues like you're describing are rather time consuming to track down and fix. I don't have much time to work on mods currently and there's quite a few other things I want to work on first.
If you want this fixed earlier, you can look into it, write a fix and submit a pull request for it. The code is all open source and you can select the branch for any version.

**Comment by Wraithypooo** [comment]
I have the same issue as original. Both tesseracts standing close.. Connected to a solar panel through wire, both from Energized Power and a wire with a mchine in the other end. No power running whatsoever. Running MC1.19.3 with Forge 44.1.0

**Comment by SuperMartijn642** [comment]
Thank you for reporting the issue.

I have made some significant changes, so this should be fixed now in Tesseract version 1.0.30. If the problem persists, please create a new issue with the relevant information.
