### ISSUE TITLE
[1.12] Issues with Thermal Expansion

### ISSUE THREAD

**Issue by Froot4** [SuperMartijn642/Tesseract#6]
I installed this mod because TE's tesseract was removed. However, I noticed that whenever I connect the tesseract to a prexisting channel for energy, it will not send/receive any. I've quadruple checked to ensure I am using the energy tab, but it still doesn't work. I have to create a new channel for every tesseract I place for it work.

**Comment by SuperMartijn642** [comment]
[Here's a video](https://youtu.be/VxHz-8E82Zg), because for me it seems to work fine.

**Comment by CloudCodePotato** [comment]
This appears to be because the power is not being split between tesseracts on the same channel, but rather given on a first come basis. If the power input is less than the output of the first connected tesseract, no power will make it to other tesseracts on the same channel.

Video: https://youtu.be/qjbrBAWBOGs

**Comment by SuperMartijn642** [comment]
Yes, this is indeed correct, all items, liquids and energy aren't distributed evenly, but just in the order the tesseracts happen to have been loaded.
I have looked at changing this before, and will probably do so in a future update.
The main reason I haven't yet is for performance.

**Comment by Froot4** [comment]
Ah yes, this looks to have solved it. Guess I was just used to TE doing it automatically.
