### ISSUE TITLE
[Crash] 1.10.27b crash as Minecraft 1.19.2 loads

### ISSUE THREAD

**Issue by JillSwift** [SuperMartijn642/Tesseract#61]
**Version Info**
- Minecraft, 1.19.2
- Tesseract, 1.10.27b (this log) (and 1.10.28)

**Steps to Reproduce**
Crashes on game loading

**Crash report (~/logs/latest.log)**
[Log Linkie](https://paste.ee/p/18QwA)

**Comment by SuperMartijn642** [comment]
Minecraft starts fine with just Tesseract and my core library.

From the log it seems like the crash is caused by 'midnight-hats':
![image](https://user-images.githubusercontent.com/12382965/210467993-f8aa2a24-a782-4757-80b9-5f5193f00265.png)

Could you check which mods are required to reproduce the issue?

**Comment by JillSwift** [comment]
Tesseract and your core and config libs _only_:
[Log Link](https://paste.ee/p/aBDHz)

**Comment by SuperMartijn642** [comment]
Looking at it now, both logs actually show Tesseract version 1.0.27, not 1.0.27b.
Could you confirm you're using version 1.0.27b (or 1.0.28 and core lib 1.1.0 for that matter)?

**Comment by JillSwift** [comment]
K, my bad, I apologize.
I hadn't seen the update to the core library.  Tesseract 1.0.28 works fine with core 1.1.0 installed.

Thank you!

**Comment by SuperMartijn642** [comment]
No worries, glad it works now 🙂
