### ISSUE TITLE
[1.12] Tesseracts in non-overworld dimensions don't resume on restart

### ISSUE THREAD

**Issue by CloudCodePotato** [SuperMartijn642/Tesseract#8]
Forge Version: 14.23.5.2846
Mod Version: tesseract-1.0.7-mc1.12

Every time the server is restarted tesseracts in dimensions other than the overworld stop functioning. 
Tested in both the nether and Aroma1997's Mining World. The same bug happens in singleplayer worlds and on multiplayer servers. For the multiplayer server, it only happens when the server restarts, not when the player leaves.

Video: https://youtu.be/gMhbiY7kdR0

**Comment by SuperMartijn642** [comment]
Whenever a save file gets loaded, the overworld seems to be loaded before other dimensions. I also validate all saved tesseracts. In 1.14, 1.15 and 1.16 this seems to be fine, however in 1.12 it won't load other dimension when the overworld isn't yet loaded.
I now moved the validation to when the world is saved, instead of when it's loaded. This should just be better in general as all dimension are already loaded at that point.

It is fixed now in version 1.0.8, thanks for the report!
