### ISSUE TITLE
1.19.2 Server crash, appears to be between Tesseract and Toms simple storage?.. 

### ISSUE THREAD

**Issue by tacogerbil** [SuperMartijn642/Tesseract#81]
**Version Info**
Minecraft 1.19.2 with Fabric Loader 0.14.22
tesseract 1.0.35

**Steps to Reproduce**
It was random.> Been using it for months and it's been pretty stable.  Maybe crashed once or twice.

**Crash report (~/logs/latest.log)**
(Next entry)

**Comment by tacogerbil** [comment]
Logs.. (sorry didn't seem to upload right)
[crash-2023-08-22_19.54.04-server.txt](https://github.com/SuperMartijn642/Tesseract/files/12414746/crash-2023-08-22_19.54.04-server.txt)
[latest.log](https://github.com/SuperMartijn642/Tesseract/files/12414747/latest.log)

**Comment by SuperMartijn642** [comment]
Seems to be caused by Tom's Simple Storage iterating over other storages when all slots are requested.
I have added checks to prevent the crash from happening now in version 1.0.35a. Ideally Tom's Simple Storage would also prevent a situation like this, since it might also happen with other mods.

Thank you for reporting the issue!

**Comment by tacogerbil** [comment]
Thank you for making such a wonderful mod!
